### ISSUE TITLE
support biolink model mixins

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#241]
Biolink model has "mixin" classes like [ChemicalOrDrugOrTreatment](https://github.com/biolink/biolink-model/blob/217a5d238286b8e39c405fbfb7e2291afb6ad783/biolink-model.yaml#L6464) which includes [ChemicalEntity](https://github.com/biolink/biolink-model/blob/217a5d238286b8e39c405fbfb7e2291afb6ad783/biolink-model.yaml#L7280), [Drug](https://github.com/biolink/biolink-model/blob/217a5d238286b8e39c405fbfb7e2291afb6ad783/biolink-model.yaml#L7666), and [Treatment](https://github.com/biolink/biolink-model/blob/217a5d238286b8e39c405fbfb7e2291afb6ad783/biolink-model.yaml#L8863).

Supporting these mixins means changes to the biolink-model JS tool, so that when a query node has the category "ChemicalOrDrugOrTreatment", BTE knows to look for operations to ChemicalEntity (and its children), Drug, and Treatment...

Another example of a mixin is [GenomicEntity](https://github.com/biolink/biolink-model/blob/217a5d238286b8e39c405fbfb7e2291afb6ad783/biolink-model.yaml#L7228), which includes [Gene](https://github.com/biolink/biolink-model/blob/217a5d238286b8e39c405fbfb7e2291afb6ad783/biolink-model.yaml#L8141)

**Comment by newgene** [comment]
So given this mixin:
```
  genomic entity:
    mixin: true
    is_a: thing with taxon
    slots:
      - has biological sequence
    in_subset:
      - translator_minimal
    narrow_mappings:
      - UMLSSC:T028   # Gene or Genome
      - GENO:0000897  # Genomic Entity
```
which is used in:
```
gene:
    description: >-
      A region (or regions) that includes all of the sequence elements
      necessary to encode a functional transcript. A gene locus may include
      regulatory regions, transcribed regions and/or other
      functional sequence regions.
    is_a: biological entity
    mixins:
      - gene or gene product
      - genomic entity
      - chemical entity or gene or gene product
      - physical essence
      - ontology class
    aliases: ['locus']
    slots:
      - symbol
      - synonym
      - xref
    exact_mappings:
      - SO:0000704
      - SIO:010035
      - WIKIDATA:Q7187
    id_prefixes:
      - NCBIGene
      - ENSEMBL
      - HGNC
      - MGI
      - ZFIN
      - dictyBase
      - WB
      - WormBase # we have two prefixes here as worbase supports WormBase:WBGene00000898
                 # and alliancegenome.org and identifiers.org supports WB:WBGene00000898.
      - FB  # FlyBase FBgn*
      - RGD
      - SGD
      - POMBASE
      - OMIM
      - KEGG.GENE ## org:gene
      - UMLS
      - Xenbase
      # - IUPHAR
    in_subset:
      - model_organism_database
```

basically, we want to merge `slots` from "genomic entity" mixin to the `slots` of the "gene" class. We can evaluate if other mixin fields should be merged, but for now `slots` looks the most relevant one.
