### ISSUE TITLE
creative/inferred mode not using `canonical_predicate` from BioLink Model

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#475]
BioLink Model specifies a `canonical_predicate` property, which is meant to indicate the direction of the edge that should be returned in TRAPI results.  For example, [treats](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L4631) is listed with `canonical_predicate: true`, and [treated_by](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L4678) lists `inverse: treats`.   See snippets from [BioLink Model](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml) below.

```
  treats:
    aliases: [ 'is substance that treats', 'indicated for' ]
    is_a: ameliorates
    description: >-
      holds between a therapeutic procedure or chemical entity
      and a disease or phenotypic feature that it is used to treat
    domain: chemical or drug or treatment
    range: disease or phenotypic feature
    annotations:
      canonical_predicate: true
      opposite_of: contraindicated for
```

```
  treated by:
    is_a: is ameliorated by
    description: >-
      holds between a disease or phenotypic feature and a therapeutic
      process or chemical entity that is used to treat the condition
    domain: disease or phenotypic feature
    range: chemical or drug or treatment
    # range: chemical or drug or treatement
    in_subset:
      - translator_minimal
    inverse: treats
```

In the context of https://github.com/NCATSTranslator/testing/issues/222, BTE's standard mode is returning edges using `biolink:treats`, but creative mode is reversing the edge and using `biolink:treated_by`.

"normal" mode: https://arax.ncats.io/?r=14e4e94c-3a77-4ad6-ac90-8df7b1e34df5

![image](https://user-images.githubusercontent.com/2635409/182425935-8fb060c0-920b-4d39-8208-30dfafd79b1f.png)

creative/inferred mode: https://arax.ncats.io/?r=ff949174-c6c8-4de9-81c7-0da9d030ee75

![image](https://user-images.githubusercontent.com/2635409/182426077-146d27ec-5c4d-45f8-b87c-f73ebc798cc8.png)
