### ISSUE TITLE
Can we populate `message.knowledge_graph.nodes.[node].name` from API output?

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#539]
In each node of `message.knowledge_graph.nodes`, there is a `name` property that is used by the ARAX UI as a human-readable label. I believe BTE populates that field using the [SRI Node Normalization service](https://nodenormalization-sri.renci.org/docs).  For example, `REACT:R-HSA-5693532` would get named `DNA Double-Strand Break Repair (Homo sapiens)` according to https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=REACT:R-HSA-5693532. 

However, there are several examples where the Node Normalization service does not provide a human readable name:
* https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=BIOCARTA:cellcyclepathway
* https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=WIKIPATHWAYS:WP466
* https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=ncats.bioplanet:bioplanet_1011

In those cases, it looks like BTE just populates that name field with the CURIE.  For example, in https://arax.ncats.io/api/arax/v1.3/response/2a8552a3-f813-425d-a748-83c4a0d1fd1f, we see this snippet:

```
"WIKIPATHWAYS:WP466": {
    "attributes": [
        {
            "attribute_type_id": "biolink:xref",
            "value": [
                "WIKIPATHWAYS:WP466"
            ]
        },
        {
            "attribute_type_id": "biolink:synonym",
            "value": [
                "WIKIPATHWAYS:WP466"
            ]
        }
    ],
    "categories": [
        "biolink:Pathway"
    ],
    "name": "WIKIPATHWAYS:WP466"
},
```

However, in some cases, the API that BTE is calling returns the name, e.g., https://mygene.info/v3/gene/1017?fields=pathway.wikipathways shows that `WP466` corresponds to `DNA Replication`. (Similarly the [Bioplanet API](https://biothings.ncats.io/bioplanet_pathway_gene) can also resolved bioplanet pathway IDs into human readable names.)  Is there a way to specify in the SmartAPI annotation a mapping between a field in the API output and the `message.knowledge_graph.nodes.[node].name` field in TRAPI? 

Motivated by https://github.com/NCATSTranslator/Feedback/issues/58

**Comment by rjawesome** [comment]
Could this go directly in the response mapping, ie.
```
  x-bte-response-mapping:
    gene:
      NCBIGene: subject.GENE_ID   ## no prefix
      pathway_name: object.PATHWAY_NAME
      pathway_categories: object.PATHWAY_CATEGORIES
      object_name: object.PATHWAY_NAME
```
Where ``subject_name`` and ``object_name`` could be specially treated fields (similar to how in this case the field NCBIGene indicates the id of the query result)

**Comment by rjawesome** [comment]
Alright, I've written some code in ``smartapi_name`` branch of api-response-transform which uses ``input_name`` and ``output_name`` in response-mapping. If it is not defined/null it falls back on node normalizer (as was done before). Example
```yaml
  x-bte-response-mapping:
    ## used for pathway-gene queries
    gene:
      NCBIGene: subject.GENE_ID   ## no prefix
      pathway_name: object.PATHWAY_NAME
      pathway_categories: object.PATHWAY_CATEGORIES
      input_name: object.PATHWAY_NAME
    ## used for gene-pathway queries
    pathway:
      "ncats.bioplanet": object.PATHWAY_ID  ## no prefix
      pathway_name: object.PATHWAY_NAME
      pathway_categories: object.PATHWAY_CATEGORIES
      output_name: object.PATHWAY_NAME
```
