### ISSUE TITLE
useful but not critical: ability to do "scrolling" GET queries with v3 Monarch API

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#789]
In https://github.com/biothings/biothings_explorer/issues/774, we migrated to the new v3 Monarch API (using the [/association endpoint](https://api-v3.monarchinitiative.org/v3/docs#/association/_get_associations_v3_api_association_get)). This is one of the [follow-up tasks](https://github.com/biothings/biothings_explorer/issues/774#issuecomment-1956088818) that would be useful to do. 

The endpoint seems to only allow us to retrieve 500 items at a time (I encountered error 500 (Internal Service Error) when trying to set the limit parameter to > 500 or to `-1`. `-1` worked w/ the old API to return all hits). 

Being able to retrieve all the items in the response would be nice, as "scrolling" GET queries. The API responses have a `total` field that tells us how many total items there are. Ex: [this](https://api-v3.monarchinitiative.org/v3/api/association?object=UBERON:0000178&category=biolink%3AGeneToExpressionSiteAssociation&subject_taxon=NCBITaxon%3A9606&predicate=biolink%3Aexpressed_in&object_namespace=UBERON&direct=true&format=json&limit=10&offset=0) has > 2000 items. 
And there is an `offset` parameter for requests, that we could use to retrieve the next 500 items, and the next, until we've retrieved all the items. 

---

Jackson says there should be code to handle scrolling GET queries already, it just needs to be applied (and customized?) for v3 Monarch API. 

They also said that it may be helpful to have an operation-level flag (like `supportBatch`) that flags operations where we want to do these scrolling GET queries. 

On thing I'm unsure of is if all cases can be handled exactly the same way though (ex: same parameter name, same field the response to look for).

**Comment by colleenXu** [comment]
@rjawesome Jackson said this may be an issue you could handle. It's not high priority though, if you have other tasks.

**Comment by rjawesome** [comment]
I added a special case to the pagination logic to support Monarch.

I also added a feature where pagination can be specified through SmartAPI yamls. For example, for the MonarchAPI the appropriate lines to be added to the yaml for a given operation would be:
```yaml
parameters:
  ...
  limit: 500
  offset: "{{ start }}" # {{ start }} is a special field in templating to denote what numbered entry the pagination is at ( similar to {{ queryInputs }})
...
pagination:
  countField: items # number of hits from this response, can point to an array (length is taken) or a numerical field
  totalField: total # field in response containing total number of hits from this request
  pageSize: 500
...
```
(these don't need to be added for Monarch since I implemented it as a special case similar to biothigns)
