### ISSUE TITLE
Pathfinder: Rework templating system

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#832]
*Parent issue: #794*

In order to better cover the space of possible pathfinder queries (in terms of pinned-node pairings), we need to revisit how Pathfinder acquires templates. Instead of manually-built TRAPI templates, we should instead generate templates on-the-fly based on the node categories presented in the pathfinder query.

Essentially, within the existing framework of the current prototype, we replace the "select templates" step as follows:

Assume two lookup tables: 

- One which takes two node-categories as coordinates, outputting an array of node-categories
- One which takes two node-categories as coordinates, outputting an array of predicates

These tables would be defined as yaml files (`categoryTable.yaml` and `predicateTable.yaml`) in the [query_graph_handler data folder](https://github.com/biothings/bte_trapi_query_graph_handler/tree/pathfinder/data), with the following structure:

```yaml
category:
  category:
    - category/predicate
    - category/predicate
   category:
     - category/predicate
     - category/predicate
category:
  category:
    - category/predicate
# and so on
```

These tables would then be used to generate templates as specified in [these slides](https://docs.google.com/presentation/d/1g0DnTrCSzUgAIpuJzK3pp0J3lR05fwd8kQqn55-o71Q/edit#slide=id.g276f6ddd617_0_0)

At which point behavior returns to the current implementation of the prototype, with one exception:

When generating final results from the existing template results (see parent issue, current prototype), skip constructing a result for any intermediate node which is not equal to or a descendant of the unpinned node category (as a computational shortcut, if the unpinned node category is `biolink:NamedThing`, then no need to check, just proceed with making the result).
